# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GaussianBlurWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GaussianBlurWindow(object):
    def setupUi(self, GaussianBlurWindow):
        GaussianBlurWindow.setObjectName("GaussianBlurWindow")
        GaussianBlurWindow.resize(422, 674)
        self.groupBox = QtWidgets.QGroupBox(GaussianBlurWindow)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 421, 671))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.lblPreview = QtWidgets.QLabel(self.groupBox)
        self.lblPreview.setGeometry(QtCore.QRect(30, 90, 371, 211))
        self.lblPreview.setText("")
        self.lblPreview.setObjectName("lblPreview")
        self.sliderSigma = QtWidgets.QSlider(self.groupBox)
        self.sliderSigma.setGeometry(QtCore.QRect(180, 630, 211, 22))
        self.sliderSigma.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSigma.setObjectName("sliderSigma")
        self.btnApply = QtWidgets.QPushButton(self.groupBox)
        self.btnApply.setGeometry(QtCore.QRect(40, 620, 93, 28))
        self.btnApply.setObjectName("btnApply")
        self.lblSgmaValue = QtWidgets.QLabel(self.groupBox)
        self.lblSgmaValue.setGeometry(QtCore.QRect(180, 590, 55, 16))
        self.lblSgmaValue.setText("")
        self.lblSgmaValue.setObjectName("lblSgmaValue")
        self.lblPreview2 = QtWidgets.QLabel(self.groupBox)
        self.lblPreview2.setGeometry(QtCore.QRect(20, 370, 371, 211))
        self.lblPreview2.setText("")
        self.lblPreview2.setObjectName("lblPreview2")
        self.lbl_sigma_value_2 = QtWidgets.QLabel(self.groupBox)
        self.lbl_sigma_value_2.setGeometry(QtCore.QRect(144, 20, 121, 20))
        self.lbl_sigma_value_2.setObjectName("lbl_sigma_value_2")
        self.lbl_sigma_value_3 = QtWidgets.QLabel(self.groupBox)
        self.lbl_sigma_value_3.setGeometry(QtCore.QRect(60, 70, 91, 16))
        self.lbl_sigma_value_3.setObjectName("lbl_sigma_value_3")
        self.lbl_sigma_value_4 = QtWidgets.QLabel(self.groupBox)
        self.lbl_sigma_value_4.setGeometry(QtCore.QRect(70, 310, 91, 20))
        self.lbl_sigma_value_4.setObjectName("lbl_sigma_value_4")

        self.retranslateUi(GaussianBlurWindow)
        QtCore.QMetaObject.connectSlotsByName(GaussianBlurWindow)

    def retranslateUi(self, GaussianBlurWindow):
        _translate = QtCore.QCoreApplication.translate
        GaussianBlurWindow.setWindowTitle(_translate("GaussianBlurWindow", "Form"))
        self.btnApply.setText(_translate("GaussianBlurWindow", "Apply"))
        self.lbl_sigma_value_2.setText(_translate("GaussianBlurWindow", "Gaussian Preview"))
        self.lbl_sigma_value_3.setText(_translate("GaussianBlurWindow", "Original Image"))
        self.lbl_sigma_value_4.setText(_translate("GaussianBlurWindow", "Final Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GaussianBlurWindow = QtWidgets.QWidget()
    ui = Ui_GaussianBlurWindow()
    ui.setupUi(GaussianBlurWindow)
    GaussianBlurWindow.show()
    sys.exit(app.exec_())
